services:
    jenkins:
        container_name: jenkins
        build: .
        image: jenkins
        ports:
            - "8081:8080"
            - "50000:50000"
        networks:
            - net
        environment: 
          - JENKINS_ADMIN_ID=admin  
          - CASC_JENKINS_CONFIG=/var/jenkins_home/cask.yaml
        volumes:
          - "jenkins_home:/var/jenkins_home"
          - "./jenkins-config/casc.yaml:/var/jenkins_home/cask.yaml"
        secrets:
          - JENKINS_ADMIN_PASSWORD

secrets:
  JENKINS_ADMIN_PASSWORD:
    file: /Users/kbogdanski/jenkins_home/JENKINS_ADMIN_PASSWORD
networks:
    net: {}
volumes:
  jenkins_home: